name: Notify Discord on Commit

on:
  push:
    branches:
      - main  # Ändra till den gren du vill övervaka

jobs:
  notify-discord:
    runs-on: ubuntu-latest

    steps:
    - name: Send Discord notification
      run: |
        curl -H "Content-Type: application/json" \
        -d "{\"content\": \"New commit pushed to the repository: $(git log -1 --pretty=format:'%s') by $(git log -1 --pretty=format:'%an').\"}" \
        ${{ secrets.DISCORD_WEBHOOK_URL }}
