name: Notify Discord on Commit

on:
  push:
    branches:
      - main

jobs:
  notify-discord:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Get commit details and send Discord notification
      run: |
        REPO_NAME=$(basename -s .git `git config --get remote.origin.url`)
        BRANCH_NAME=${GITHUB_REF#refs/heads/}
        COMMIT_HASH=$(git log -1 --pretty=format:'%h')
        COMMIT_MESSAGE=$(git log -1 --pretty=format:'%s')
        AUTHOR_USERNAME=${{ github.actor }}
        COMMIT_URL="${{ github.server_url }}/${{ github.repository }}/commit/$COMMIT_HASH"
        AUTHOR_URL="https://github.com/${{ github.actor }}"
        AVATAR_URL="https://avatars.githubusercontent.com/u/${{ github.actor_id }}"

        DISCORD_MESSAGE="{
          \"content\": null,
          \"embeds\": [
            {
              \"title\": \"[[$REPO_NAME:$BRANCH_NAME]]($COMMIT_URL) 1 new commit.\",
              \"description\": \"[\`$COMMIT_HASH\`]($COMMIT_URL) $COMMIT_MESSAGE\",
              \"color\": 938306,
              \"author\": {
                \"name\": \"$AUTHOR_USERNAME\",
                \"url\": \"$AUTHOR_URL\",
                \"icon_url\": \"$AVATAR_URL\"
              }
            }
          ],
          \"attachments\": []
        }"

        echo $DISCORD_MESSAGE > message.json

    - name: Send Discord notification
      run: |
        curl -H "Content-Type: application/json" \
        -d @message.json \
        ${{ secrets.DISCORD_WEBHOOK_URL }}